### ISSUE TITLE
hey cutie

### ISSUE THREAD

**Issue by mte0** [FlashSkyNews/TagConverter#1]
hey i was wondering if u actually made that twitch sub farm bot? the repo just be empty rn.

**Comment by FlashSkyNews** [comment]
Hey, sorry for responding so late

Sadly no, I didn't have the time to do so but it would be very simple
Use the dank-twitch-irc JS-Library to interact with twitch and then just join predefined channels in a channels.json or something like that :)

**Comment by FlashSkyNews** [comment]
Okay, just saw that the dank-twitch-irc's dev stopped supporting it. It probably still should work tho

just made this, maybe it works maybe not, idk i just copy pasted from older repos :)


Create a new folder for the bot
Open term or cmd
> npm install dank-twitch-irc (if you haven't got npm/nodejs install it)
> create a main.js and paste that in:
`
// Init libraries and files
const { ChatClient } = require('dank-twitch-irc')
const fs = require('fs');
const config = require('./config.json');

// Define login
let client = new ChatClient({
    username: config.username,
    password: config.oauth,
});


// Login
client.on('ready', () => {
    console.log('Successfully connected to Twitch');
});
client.on('close', (error) => {
    if (error != null) {
        console.error(CTERROR + 'Client closed due to error', error);
    }
});

client.connect();
client.joinAll(config.channels)
`

also create a config.json in the same folder:
`
{
    "username": "youttwitchaccount", // Your Twitch account you want to farm subs on
    "oauth": "oauth:youroauthkey" // https://twitchapps.com/tmi/
    "channels": "channel1, channel2, channel3" // Limit per instance would be ~100 Channels
}
`
